### ISSUE TITLE
Production deploy seems incorrect?

### ISSUE THREAD

**Issue by polarathene** [traefik/seo-doc#2]
https://github.com/traefik/seo-doc/blob/90039c8f766d855f20caf31c56465cb4b1800add/core.go#L73

https://github.com/traefik/seo-doc/blob/90039c8f766d855f20caf31c56465cb4b1800add/core.go#L30

[The Traefik CI workflow](https://github.com/traefik/traefik/blob/606b43dc512fbeceb79d756a6ddcf796676dc884/.github/workflows/documentation.yml#L47):

```yml
- name: Apply seo
  run: $HOME/bin/seo -path=./site
```

Results in older docs (https://doc.traefik.io/traefik/v2.0/providers/docker/) using `<link rel="canonical" href="https://doc.traefik.io/site/">` (which is 404 of course).

I imagine it was meant to be `<link rel="canonical" href="https://doc.traefik.io/traefik/">` or `<link rel="canonical" href="https://doc.traefik.io/traefik/providers/docker/">`?

---

[Likewise the page title](https://doc.traefik.io/traefik/v2.0/providers/overview/) is `Overview - Traefik | Site | v2.0` instead of the described expectation of `Overview | Traefik | v2.0`.

---

`structor` is also being used in [that workflow and referencing Dockerfile from Traefik 1.7](https://github.com/traefik/traefik/blob/606b43dc512fbeceb79d756a6ddcf796676dc884/.github/workflows/documentation.yml#L42)? Not sure if that's an accident that got overlooked, but thought I'd mention it :)

**Comment by ldez** [comment]
Fixed by 605749df5b10d97d32b2d006d143067b35cc4a1b
